/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ClasesEditoras.JPEGImageCopy;
import ClasesEditoras.JPEGImageHandlerBN;
import ClasesEditoras.JPEGImageHandlerColors;
import ClasesEditoras.JPEGImageHandlerRotator;
import ClasesEditoras.JPEGtoBMPImage;
import datos.Doble;
import datos.ListaDoble;
import datos.UsuarioNodo;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.*;
import proyecto2.JPEGHandler;




public class EditorVista extends javax.swing.JFrame {
    Doble componente; 
    ListaDoble lista2 = new ListaDoble(); 
    
    
   private UsuarioNodo imagen2;
   
   String fileName;
    public EditorVista() {
        
        this.componente = new Doble(lista2); 
        
        initComponents();
    }

    
    
    // funcion para agregar la imagen al jlabel
    public void setImagen(String ruta) {
        ImageIcon imagen = new ImageIcon(ruta);
        imagen2.setIcon(imagen);
        imagen2.setSize(imagen.getIconWidth(), imagen.getIconHeight());
        repaint();
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel1 = new javax.swing.JLabel();
        seleccionar = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        labelimagen = new javax.swing.JLabel();
        copia = new javax.swing.JButton();
        copia2 = new javax.swing.JButton();
        colores = new javax.swing.JButton();
        bn = new javax.swing.JButton();
        rotar = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        seleccionar.setText("seleccionar imagen");
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(labelimagen)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(labelimagen)
                .addContainerGap(468, Short.MAX_VALUE))
        );

        copia.setText("JPEG a BMP ");
        copia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiaActionPerformed(evt);
            }
        });

        copia2.setText("copia JPEG");
        copia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copia2ActionPerformed(evt);
            }
        });

        colores.setText("Rojo, Verde,Azul y sepia");
        colores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coloresActionPerformed(evt);
            }
        });

        bn.setText("Blanco y negro");
        bn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnActionPerformed(evt);
            }
        });

        rotar.setText("Rotar");
        rotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colores, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(copia, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(copia2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(copia)
                        .addGap(52, 52, 52)
                        .addComponent(copia2)
                        .addGap(52, 52, 52)
                        .addComponent(colores)
                        .addGap(61, 61, 61)
                        .addComponent(bn)
                        .addGap(61, 61, 61)
                        .addComponent(rotar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
    JFileChooser filechooser = new JFileChooser();    
    filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int result = filechooser.showOpenDialog(null); 
    if(result == JFileChooser.APPROVE_OPTION){
        File choosedFileName = filechooser.getSelectedFile(); 
        System.out.println(choosedFileName);
        fileName = choosedFileName.toString(); 
    }
       
        
    }//GEN-LAST:event_seleccionarActionPerformed

    private void coloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloresActionPerformed
       try{
          JPEGHandler.runHandler(new JPEGImageHandlerColors(fileName));
      }catch(Exception exception){
          exception.printStackTrace();
      }  
    }//GEN-LAST:event_coloresActionPerformed

    private void copiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiaActionPerformed
      try{
          JPEGHandler.runHandler(new JPEGtoBMPImage(fileName));
      }catch(Exception exception){
          exception.printStackTrace();
      }
    }//GEN-LAST:event_copiaActionPerformed

    private void copia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copia2ActionPerformed
       try{
          JPEGHandler.runHandler(new JPEGImageCopy(fileName));
      }catch(Exception exception){
          exception.printStackTrace();
      }
    }//GEN-LAST:event_copia2ActionPerformed

    private void rotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotarActionPerformed
         try{
          JPEGHandler.runHandler(new JPEGImageHandlerRotator(fileName));
      }catch(Exception exception){
          exception.printStackTrace();
      }
    }//GEN-LAST:event_rotarActionPerformed

    private void bnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnActionPerformed
        try{
          JPEGHandler.runHandler(new JPEGImageHandlerBN(fileName));
      }catch(Exception exception){
          exception.printStackTrace();
      }
    }//GEN-LAST:event_bnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn;
    private javax.swing.JButton colores;
    private javax.swing.JButton copia;
    private javax.swing.JButton copia2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel labelimagen;
    private javax.swing.JPanel panel2;
    private javax.swing.JButton rotar;
    private javax.swing.JButton seleccionar;
    // End of variables declaration//GEN-END:variables
}
